-- RecruitmentOS AI portfolio schema
-- Run in a new Supabase project. Use synthetic data for public demonstrations.

create table public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  company text,
  email text,
  phone text,
  placement_fee_percentage numeric(5,2) not null default 0,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.vacancies (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  title text not null,
  department text,
  location text,
  employment_type text,
  description text,
  status text not null default 'open',
  salary_min numeric(14,2),
  salary_max numeric(14,2),
  currency text not null default 'USD',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.candidates (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  phone text,
  current_title text,
  status text not null default 'active',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.applications (
  id bigint generated by default as identity primary key,
  vacancy_id bigint not null references public.vacancies(id) on delete cascade,
  candidate_id bigint not null references public.candidates(id) on delete cascade,
  status text not null default 'active',
  stage text,
  source text,
  notes text,
  last_activity_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (vacancy_id, candidate_id)
);

create table public.interviews (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.applications(id) on delete cascade,
  scheduled_at timestamptz,
  interview_type text,
  interviewer text,
  location text,
  status text not null default 'scheduled',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  task_type text,
  priority text not null default 'medium' check (priority in ('high', 'medium', 'low')),
  status text not null default 'pending',
  due_at timestamptz,
  completed_at timestamptz,
  assigned_to text,
  client_id bigint references public.clients(id) on delete set null,
  vacancy_id bigint references public.vacancies(id) on delete set null,
  application_id bigint references public.applications(id) on delete cascade,
  source text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.activities (
  id bigint generated by default as identity primary key,
  application_id bigint references public.applications(id) on delete cascade,
  candidate_id bigint references public.candidates(id) on delete set null,
  vacancy_id bigint references public.vacancies(id) on delete set null,
  client_id bigint references public.clients(id) on delete set null,
  activity_type text not null,
  description text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.ai_recommendations (
  id bigint generated by default as identity primary key,
  recommendation_type text not null,
  title text not null,
  reasoning text,
  recommended_action text not null,
  priority text not null check (priority in ('high', 'medium', 'low')),
  status text not null default 'pending',
  confidence_score integer check (confidence_score between 0 and 100),
  risk_score integer check (risk_score between 0 and 100),
  revenue_at_risk numeric(14,2) not null default 0,
  currency text not null default 'USD',
  client_id bigint references public.clients(id) on delete set null,
  vacancy_id bigint references public.vacancies(id) on delete set null,
  candidate_id bigint references public.candidates(id) on delete set null,
  application_id bigint references public.applications(id) on delete cascade,
  task_id bigint references public.tasks(id) on delete set null,
  generated_at timestamptz not null default now(),
  expires_at timestamptz,
  model_used text,
  input_snapshot jsonb not null default '{}'::jsonb,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index applications_status_idx on public.applications(status);
create index applications_last_activity_idx on public.applications(last_activity_at);
create index interviews_application_schedule_idx on public.interviews(application_id, scheduled_at);
create index tasks_application_status_idx on public.tasks(application_id, status);
create index activities_application_created_idx on public.activities(application_id, created_at desc);
create index ai_recommendations_duplicate_check_idx
  on public.ai_recommendations(application_id, recommendation_type, status);

alter table public.clients enable row level security;
alter table public.vacancies enable row level security;
alter table public.candidates enable row level security;
alter table public.applications enable row level security;
alter table public.interviews enable row level security;
alter table public.tasks enable row level security;
alter table public.activities enable row level security;
alter table public.ai_recommendations enable row level security;

-- This portfolio workflow expects server-side access through n8n.
-- Store the Supabase service-role key only in n8n's encrypted credential store.
-- Create narrower database roles/policies for a production client deployment.

